language: go

go:
  - 1.5.4
  - 1.6

services:
  - redis-server
  - docker

install:
  - make dependencies

script:
  - make stat test

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/beacon unixvoid/beacon:develop
  - docker push unixvoid/beacon
