language: go

go:
  - 1.5.4
  - 1.6

services:
  - redis-server
  - docker

install:
  - make dependencies

script:
  - make stat test

after_success:
  - make clean
  - make docker
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag unixvoid/beacon unixvoid/beacon:develop
  - docker push unixvoid/beacon:develop
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon*` --form path=beacon/ https://cryo.unixvoid.com/upload
  - curl -i --form sec=$BINDER_SEC --form file=@`ls bin/beacon*` --form filename=beacon-latest-linux-amd64 --form path=beacon/ https://cryo.unixvoid.com/upload
